[platformio]
; 告诉 PlatformIO 源码在 Core/Src，头文件在 Core/Inc
src_dir = Core/Src
include_dir = Core/Inc

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
; 使用原生的 STM32Cube HAL 框架
framework = stm32cube

; 添加头文件搜索路径，消除 main.c 里的红线
build_flags =
    -I Core/Inc

; 烧录与调试方式
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200